// ============================================
// AgriSwitch AI — PDF Generation Utility
// ============================================

import jsPDF from 'jspdf';

/**
 * Generate a PDF document from text content.
 * Used for subsidy application drafts and transition reports.
 */
export function generatePDF(
    title: string,
    content: string,
    fileName: string
): void {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    const maxWidth = pageWidth - margin * 2;

    // Title
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text(title, margin, 25);

    // Horizontal line
    doc.setLineWidth(0.5);
    doc.line(margin, 30, pageWidth - margin, 30);

    // Content
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');

    const lines = doc.splitTextToSize(content, maxWidth);
    let y = 40;

    for (const line of lines) {
        if (y > 270) {
            doc.addPage();
            y = 20;
        }
        doc.text(line, margin, y);
        y += 6;
    }

    // Footer
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(128);
        doc.text(
            `Generated by AgriSwitch AI — Page ${i} of ${pageCount}`,
            margin,
            doc.internal.pageSize.getHeight() - 10
        );
        doc.text(
            'Disclaimer: This is a computer-generated draft. Please verify all details before submission.',
            margin,
            doc.internal.pageSize.getHeight() - 5
        );
    }

    doc.save(fileName);
}
