// ============================================
// AgriSwitch AI — Deterministic Calculation Constants
// ============================================
// All values are based on published agricultural research
// and government scheme documents. These are NOT generated by LLM.

export const CALCULATION_CONSTANTS = {
    // Residue generation
    RESIDUE_PER_ACRE_TONS: 2.5,

    // Emissions from burning
    CO2_PER_ACRE_BURNED_TONS: 2.5,

    // Burning costs (minimal labor cost for setting fire)
    BURN_LABOR_COST_PER_ACRE: 500,

    // Sustainable management costs
    MACHINERY_RENTAL_COST_PER_ACRE: 2500,  // Happy Seeder / SMS rental
    MACHINERY_PURCHASE_SUBSIDY_PERCENT: 0.40,  // 40% CRM subsidy

    // Long-term benefits
    SOIL_PRODUCTIVITY_GAIN_PERCENT: 0.03,    // 3% over 3 seasons
    AVERAGE_YIELD_VALUE_PER_ACRE: 45000,     // ₹ average seasonal revenue

    // Carbon credits
    CARBON_PRICE_PER_TON: 800,    // ₹ per ton CO₂

    // Environmental equivalents
    TREES_PER_TON_CO2: 45,            // trees needed to absorb 1 ton CO₂/year
    CARS_PER_TON_CO2_YEAR: 0.22,      // cars emitting 1 ton CO₂/year

    // Seasons for projection
    PROJECTION_SEASONS: 3,
} as const;

/** State-specific adjustments */
export const STATE_ADJUSTMENTS: Record<string, { laborMultiplier: number; subsidyBonus: number }> = {
    'Punjab': { laborMultiplier: 1.0, subsidyBonus: 0.10 },
    'Haryana': { laborMultiplier: 0.95, subsidyBonus: 0.15 },
    'Uttar Pradesh': { laborMultiplier: 0.85, subsidyBonus: 0.05 },
};

/** Default farm profile values for the wizard */
export const DEFAULT_FARM_VALUES = {
    landSizeAcres: 5,
    state: 'Punjab' as const,
    cropType: 'Paddy' as const,
    machineryAccess: false,
    laborCostPerAcre: 500,
    dieselPrice: 95,
};
